server:
  port: 8004
spring:
  application:
    name: ms-hystrix-consumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://ljf:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
       business: Provide ms-fegin-client
       project-team: java-team
       cluster: ljf-turbine
#将feging中的超时熔断机制给关掉
feign:
  hystrix:
    enabled: true
#设置默认的服务超时时间为5s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#设置查看指标
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"