security:
  basic:
    enabled: true
  user:
    name: ljf
    password: 123
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false   #当做server，不当做client
    fetch-registry: false
    service-url:
      defaultZone: http://ljf:123@localhost:8761/eureka
  #关闭自我保护模式，false关闭，true打开
  server:
      enableSelfPreservation: true
  #环境的说明
  environment: weifuwu
  datacenter: weifuwu-cloud