security:
  basic:
    enabled: true
  user:
    name: ljf
    password: 123
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false   #当做server，不当做client
    fetch-registry: false
    service-url:
      defaultZone: http://ljf:123@localhost:8761/eureka