server:
  port: 8001
spring:
  application:
    name: ms-ribbon-yml-consumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://ljf:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

#ms-eureka-provider:
 # ribbon:
  #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon 脱离eureka实现负载均衡
ribbon:
  eureka:
   enabled: false
ms-eureka-provider:
  ribbon:
    listOfServers: localhost:7900